parent=keycloak
import=common/keycloak

styles=css/patternfly.min.css css/patternfly.min.css css/patternfly-additions.min.css css/pficon.css css/login.css
backToAppUrl=${env.BACK_TO_APP_URL:https://bluepay-v0.onrender.com}
